[versions]
kotlin = "2.0.0"

[libraries]
kotlin-plugin = { module = "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin", version.ref = "kotlin" }
dokka-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version = "1.9.20" }
spotless-plugin = { module = "com.diffplug.spotless:spotless-plugin-gradle", version = "6.25.0" }

[plugins]
kotlin-dsl = { id = "org.gradle.kotlin.kotlin-dsl", version = "5.1.0" }
