---
# TODO: portlek, Implement the publish command.
name: "Release"
"on":
  release:
    types:
    - "released"
jobs:
  build:
    name: "Release"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@master"
    - uses: "actions/setup-java@master"
      with:
        distribution: "adopt"
        java-version: "11"
    - uses: "actions/cache@master"
      with:
        path: "~/.gradle/caches"
        key: "${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle.kts') }}"
        restore-keys: |
          ${{ runner.os }}-gradle-
    - uses: "actions/cache@master"
      with:
        path: "~/.gradle/wrapper"
        key: "${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle-wrapper.properties') }}"
        restore-keys: |
          ${{ runner.os }}-gradlew-
    - run: |
        [[ "${{ github.event.release.tag_name }}" =~ ^[0-9]+(\.[0-9]+)*$ ]] || exit -1
        chmod +x gradlew
        ./gradlew
